# Tasks only performed on nodes
---
- name: ensure cni config directory exists
  file:
    path: /etc/cni/net.d
    state: directory

- name: generate CNI config file
  template:
    src: bridge-v6.conf.j2
    dest: /etc/cni/net.d/10-bridge-v6.conf
