---
# root work
- block:
    - name: Add vpp repo
      yum_repository:
        name: fdio-release
        description: fd.io release branch latest merge
        baseurl: https://nexus.fd.io/content/repositories/fd.io.centos7/
        gpgcheck: 0
    - name: Install vpp
      package:
        name: vpp
        state: present
    - name: Install vpp-plugins
      package:
        name: vpp-plugins
        state: present
  become: true
  become_user: root
