---
# - hosts: master,nodes
#   become: true
#   become_user: root
#   tasks: []
#   roles:
#     - { role: glusterfs-install }

# - hosts: master
#   become: true
#   become_user: root
#   tasks: []
#   roles:
#     - { role: glusterfs-probe-peers }
#     - { role: glusterfs-create-volume, volume_appendix: 1 }
#     - { role: glusterfs-create-volume, volume_appendix: 2 }
#     - { role: glusterfs-create-volume, volume_appendix: 3 }
#     - { role: glusterfs-create-volume, volume_appendix: 4 }
#     - { role: glusterfs-create-volume, volume_appendix: 5 }

- hosts: nodes
  become: true
  become_user: root
  tasks: 
    - name: Install mount.glusterfs
      yum:
        name: glusterfs-fuse
        state: present

- hosts: master
  tasks: []
  roles:
    - { role: glusterfs-kube-config }
