---
- hosts: kube-nat64-dns64
  become: true
  become_user: root
  tasks:
    - name: update kernel
      package:
        name: kernel
        state: latest
      notify: "restart server"
  handlers:
    - include: roles/ipv6-setup/handlers/main.yml
      static: yes

- hosts: all
  become: true
  become_user: root
  tasks: []
  roles:
    - { role: ipv6-setup }

- hosts: master,nodes
  become: true
  become_user: root
  tasks:
    - name: Remove default ipv4 route
      shell: |
        if ip route | grep default; then
          ip route delete default via 192.168.122.1 dev eth0
        fi

- hosts: kube-master
  become: true
  become_user: root
  tasks:
    - name: configure routing
      lineinfile:
        path: /etc/sysconfig/network-scripts/route6-eth1
        create: yes
        line: "{{ item }}"
      with_items:
        - "64:ff9b::/96 via fd00::64 metric 1024"
        - "fd00:101::/64 via fd00::101 metric 1024"
        - "fd00:102::/64 via fd00::102 metric 1024"
      notify: "restart eth1"
  handlers:
    - include: roles/ipv6-setup/handlers/main.yml
      static: yes

- hosts: kube-node-1
  become: true
  become_user: root
  tasks:
    - name: configure routing
      lineinfile:
        path: /etc/sysconfig/network-scripts/route6-eth1
        create: yes
        line: "{{ item }}"
      with_items:
        - "64:ff9b::/96 via fd00::64 metric 1024"
        - "fd00:1234::/64 via fd00::100 metric 1024"
        - "fd00:102::/64 via fd00::102 metric 1024"
      notify: "restart eth1"
  handlers:
    - include: roles/ipv6-setup/handlers/main.yml
      static: yes


- hosts: kube-node-2
  become: true
  become_user: root
  tasks:
    - name: configure routing
      lineinfile:
        path: /etc/sysconfig/network-scripts/route6-eth1
        create: yes
        line: "{{ item }}"
      with_items:
        - "64:ff9b::/96 via fd00::64 metric 1024"
        - "fd00:1234::/64 via fd00::100 metric 1024"
        - "fd00:101::/64 via fd00::101 metric 1024"
      notify: "restart eth1"
  handlers:
    - include: roles/ipv6-setup/handlers/main.yml
      static: yes

- hosts: kube-nat64-dns64
  become: true
  become_user: root
  tasks:
    - name: configure routing
      lineinfile:
        path: /etc/sysconfig/network-scripts/route6-eth1
        create: yes
        line: "{{ item }}"
      with_items:
        - "fd00:101::/64 via fd00::101 metric 1024"
        - "fd00:102::/64 via fd00::102 metric 1024"
      notify: "restart eth1"
  handlers:
    - include: roles/ipv6-setup/handlers/main.yml
      static: yes

- hosts: kube-nat64-dns64
  become: true
  become_user: root
  tasks:
    - name: install the 'Development tools' package group
      package:
        name: "@Development tools"
        state: latest
    - name: install packages
      package:
        name: "{{ item }}"
        state: latest
      with_items:
        - kernel-devel
        - pkgconfig
        - libnl3-devel
    - name: install jool
      shell: |
        if ! /usr/local/bin/jool --v; then
          cd
          git clone https://github.com/NICMx/jool.git
          cd jool/mod
          make
          make install
          cd ../usr
          ./autogen.sh
          ./configure
          make
          make install
        fi
    - name: load jool kernel module
      modprobe:
        name: jool
        state: present
        params: "pool6=64:ff9b::/96 disabled"
    - name: set pool4 range and enable jool
      shell: |
        /usr/local/bin/jool -4 --add {{ ansible_host }} 7000-8000
        /usr/local/bin/jool --enable
    - name: Configure named
      block:
        - lineinfile:
            path: /etc/named.conf
            line: 'allow-query { any; };'
            regexp: 'allow-query\s'
          notify:
            - restart named
        - lineinfile:
            path: /etc/named.conf
            line: 'forwarders { 192.168.122.1; };'
            regexp: 'forwarders\s'
            insertafter: 'allow-query\s'
          notify:
            - restart named
        - lineinfile:
            path: /etc/named.conf
            regexp: 'dnssec-validation\s'
            state: absent
          notify:
            - restart named
        - lineinfile:
            path: /etc/named.conf
            line: 'listen-on-v6 { any; };'
            regexp: 'listen-on-v6\s'
          notify:
            - restart named
        - lineinfile:
            path: /etc/named.conf
            line: 'dns64 64:ff9b::/96 { exclude { any; }; };'
            regexp: 'dns64\s'
            insertafter: 'listen-on-v6\s'
          notify:
            - restart named
        - service:
            name: named
            state: started
            enabled: true
  handlers:
    - name: restart named
      service:
        name: named
        state: restarted

- hosts: master,nodes
  become: true
  become_user: root
  tasks:
    - name: ping nat64 node
      shell: ping6 -c 5 fd00::64
      register: ping_nat64_result
    - assert:
        that:
          "ping_nat64_result.rc == 0"
    - name: ping google's ipv6 address
      shell: ping6 -c 5 64:ff9b::216.58.217.78
      register: ping_google_result
    - assert:
        that:
          "ping_google_result.rc == 0"

- hosts: master,nodes
  become: true
  become_user: root
  tasks:
    - include_role:
        name: ipv6-setup
        tasks_from: nodes
