---
- include: ipv6-lab.yml
  when: ipv6_enabled

- hosts: master,nodes
  become: true
  become_user: root
  tasks: []
  roles:
    # - { role: docker-install }
    # You can add "crio_force: true" if you need to run the builds again.
    - { role: go-install, when: container_runtime == 'crio' }
    - { role: cri-o-install, when: container_runtime == 'crio', crio_force: false }
    - { role: buildah-install, when: container_runtime == 'crio' }
    - { role: kube-install }
    - { role: multus-cni, when: pod_network_type == "multus" }

- hosts: master,nodes
  become: true
  become_user: root
  tasks:
    - name: Set bridge-nf-call-iptables to 1
      shell: >
        echo "1" > /proc/sys/net/bridge/bridge-nf-call-iptables

- hosts: master
  become: true
  become_user: root
  tasks: []
  roles:
    - { role: kube-init }
    - { role: kube-template-cni }

# ---- placeholder: kube-cni
# without become.

- hosts: master
  tasks: []
  roles:
    - { role: kube-cni }
    - { role: kube-niceties }


- hosts: master
  tasks: []
  roles:
    - { role: multus-crd, when: "pod_network_type == 'multus' and multus_use_crd"}

- hosts: nodes
  become: true
  become_user: root
  pre_tasks:
    - name: Get kubeadm_join_command from master
      set_fact:
        kubeadm_join_command: "{{ hostvars[groups['master'][0]]['kubeadm_join_command'] }}"
  tasks: []
  roles:
    - { role: kube-join-cluster }

- hosts: master
  become: true
  become_user: root
  tasks: []
  roles:
    - { role: kubectl-proxy-systemd }
