---
- src: https://github.com/gantsign/ansible-role-golang
  name: install-go
  version: master
- src: https://github.com/pmossakx/ansible-role-docker
  name: install-docker
  version: master
- src: https://github.com/redhat-nfvpe/auto-kube-dev
  name: auto-kube-dev
  version: master
- src: https://github.com/redhat-nfvpe/ansible-role-vm-spinup
  name: redhat-nfvpe.vm-spinup
  version: master
- src: https://github.com/redhat-nfvpe/ansible-role-prometheus-operator
  name: redhat-nfvpe.prometheus-operator
  version: master
