---

- name: shut down eth1
  shell: ifdown eth1
  listen: "restart eth1"

- pause:
    seconds: 2
  listen: "restart eth1"

- name: bring up eth1
  shell: ifup eth1
  listen: "restart eth1"

- name: shut down eth1.1
  shell: ifdown eth1.1
  listen: "restart eth1.1"
  when: "'master' in group_names"

- pause:
    seconds: 2
  listen: "restart eth1.1"

- name: bring up eth1.1
  shell: ifup eth1.1
  listen: "restart eth1.1"
  when: "'master' in group_names"
