---

- name: shut down eth1
  command: ifdown eth1
  listen: "restart eth1"

- name: restart eth1
  pause:
    seconds: 2
  listen: "restart eth1"

- name: bring up eth1
  command: ifup eth1
  listen: "restart eth1"

- name: shut down eth1.1
  command: ifdown eth1.1
  listen: "restart eth1.1"
  when: "'master' in group_names"

- name: restart eth1.1
  pause:
    seconds: 2
  listen: "restart eth1.1"

- name: bring up eth1.1
  command: ifup eth1.1
  listen: "restart eth1.1"
  when: "'master' in group_names"
