all:
  hosts:
    virthost:
      ansible_host: 192.168.1.42
      ansible_ssh_user: root
      bridge_networking: false
      virtual_machines:
        - name: kube-master
          node_type: master
        - name: kube-node-1
          node_type: nodes
        - name: kube-node-2
          node_type: nodes
        - name: kube-nat64-dns64
          node_type: other
      ipv6_enabled: true
