---
- name: Destroy all VMs
  shell: >
    virsh destroy {{ item }}
  with_items: "{{ virtual_machines }}"
  ignore_errors: yes

- name: Undefine all VMs
  shell: >
    virsh undefine --remove-all-storage {{ item }}
  with_items: "{{ virtual_machines }}"
  ignore_errors: yes

- name: Remove spare disk images
  file:
    dest: "{{ spare_disk_location }}/{{ item }}.img"
    state: absent
  with_items: "{{ virtual_machines }}"

- name: Remove spare disk attached semaphor
  file:
    dest: "{{ spare_disk_location }}/.attached-{{ item }}"
    state: absent
  with_items: "{{ virtual_machines }}"
