---
# Some (lots!) borrowed from https://github.com/cri-o/cri-o-ansible

- name: Create a path for us
  set_fact:
    extended_path: "/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/centos/.local/bin:/home/centos/bin/:/usr/local/go/bin"

- name: Install required packages for cri-o
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - wget
    - git
    - make
    - gcc
    - tar
    - libseccomp-devel
    - glib2-devel
    - glibc-static
    - container-selinux
    - btrfs-progs-devel
    - device-mapper-devel
    - glibc-devel
    - gpgme-devel
    - libassuan-devel
    - libgpg-error-devel
    - pkgconfig
    - json-glib-devel
    - skopeo-containers
    - ostree
    - ostree-devel
    - iptables

- name: Make directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
       - /etc/systemd/system/kubelet.service.d/
       - /var/lib/etcd
       - /etc/cni/net.d
       - /etc/containers

- name: clone runc
  git:
    repo: https://github.com/opencontainers/runc
    dest: "{{ ansible_env.HOME }}/{{ gopath }}/src/github.com/opencontainers/runc"
    version: master

- name: clone CRI-O
  git:
    repo: "{{ crio_giturl|default('https://github.com/cri-o/cri-o.git') }}"
    dest: "{{ ansible_env.HOME }}/{{ gopath }}/src/github.com/cri-o/cri-o"
    version: "{{ crio_version|default('master') }}"

- name: clone conmon
  git:
    repo: https://github.com/containers/conmon.git
    dest: "{{ ansible_env.HOME }}/{{ gopath }}/src/github.com/containers/conmon"
    version: master

- name: clone cri-tools
  git:
    repo: https://github.com/kubernetes-sigs/cri-tools.git
    dest: "{{ ansible_env.HOME }}/{{ gopath }}/src/github.com/kubernetes-sigs/cri-tools"
    version: master

- name: clone CNI
  git:
    repo: https://github.com/containernetworking/plugins
    dest: "{{ ansible_env.HOME }}/{{ gopath }}/src/github.com/containernetworking/plugins"
    version: master

- name: build runc # noqa 301
  shell: |
          cd {{ ansible_env.HOME }}/{{ gopath }}/src/github.com/opencontainers/runc && \
          export GOPATH={{ ansible_env.HOME }}/{{ gopath }} && \
          make BUILDTAGS="seccomp selinux" && make install
  environment:
    PATH: "{{ extended_path }}"

- name: link runc # noqa 301
  file:
    src: /usr/local/sbin/runc
    dest: /usr/bin/runc
    state: link

- name: build cri-o # noqa 301
  shell: |
          cd {{ ansible_env.HOME }}/{{ gopath }}/src/github.com/cri-o/cri-o && \
          make && \
          make install && \
          make install.systemd && \
          make install.config
  environment:
    PATH: "{{ extended_path }}"
    GOPATH: "{{ ansible_env.HOME }}/{{ gopath }}"

- name: build conmon # noqa 301
  shell: |
          cd {{ ansible_env.HOME }}/{{ gopath }}/src/github.com/containers/conmon && \
          make && \
          make install
  environment:
    PATH: "{{ extended_path }}"
    GOPATH: "{{ ansible_env.HOME }}/{{ gopath }}"

- name: build cri-tools # noqa 301
  shell: |
          cd {{ ansible_env.HOME }}/{{ gopath }}/src/github.com/kubernetes-sigs/cri-tools && \
          make && \
          make install
  environment:
    PATH: "{{ extended_path }}"
    GOPATH: "{{ ansible_env.HOME }}/{{ gopath }}"

- name: build CNI stuff # noqa 301
  shell: |
          cd {{ ansible_env.HOME }}/{{ gopath }}/src/github.com/containernetworking/plugins && \
          ./build_linux.sh && \
          mkdir -p /opt/cni/bin && \
          cp bin/* /opt/cni/bin/
  environment:
    PATH: "{{ extended_path }}"

- name: run CRI-O with systemd cgroup manager
  replace:
    regexp: 'cgroupfs'
    replace: 'systemd'
    name: /etc/crio/crio.conf
    backup: yes

- name: enable and start CRI-O
  systemd:
    name: crio
    state: started
    enabled: yes
    daemon_reload: yes

- name: modprobe br_netfilter
  modprobe:
    name: br_netfilter
    state: present

- name: tune sysctl
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: '1'
    reload: yes
    state: present
    sysctl_set: yes
    sysctl_file: /etc/sysctl.conf

- name: systemd dropin for kubeadm # noqa 301
  shell: >
          sh -c 'echo "[Service]
          Environment=\"KUBELET_EXTRA_ARGS=--container-runtime=remote
          --runtime-request-timeout=15m --image-service-endpoint /var/run/crio/crio.sock
          --container-runtime-endpoint /var/run/crio/crio.sock\"" > /etc/systemd/system/kubelet.service.d/0-crio.conf'

- name: flush iptables
  iptables:
    chain: "{{ item }}"
    flush: yes
  with_items:  [ 'INPUT', 'FORWARD', 'OUTPUT' ]
