---
# --------------------------------------------
# This is used for Multus CNI prior to v2.0
# --------------------------------------------
# crd_namespace: "kubernetes.cni.cncf.io"
# multus_use_default_network: true
# multus_version: "dev/network-plumbing-working-group-crd-change"
# multus_git_url: "https://github.com/Intel-Corp/multus-cni.git"
crd_name_proper: "networks"
bridge_networking: true
bridge_name: br0
bridge_physical_nic: "enp1s0f1"
bridge_network_name: "br0"
bridge_network_cidr: 192.168.1.0/24
pod_network_type: "multus"
virtual_machines:
  - name: kube-multus-master
    node_type: master
  - name: kube-multus-node-1
    node_type: nodes
optional_packages:
  - tcpdump
  - bind-utils
multus_use_crd: true
multus_legacy: true
multus_ipam_subnet: "192.168.1.0/24"
multus_ipam_rangeStart: "192.168.1.200"
multus_ipam_rangeEnd: "192.168.1.216"
multus_ipam_gateway: "192.168.1.1"
multus_macvlan_master: "eth0"