---
- name: Install bridge-utils and firewalld # noqa 403
  yum:
    name: bridge-utils,firewalld
    state: latest

- name: enable firewalld
  systemd:
    name: firewalld
    state: started
    enabled: yes

- name: Accept bridge forwarding and accept packets # noqa 301
  shell: >
    firewall-cmd --permanent --direct --passthrough ipv4 -I FORWARD -m physdev --physdev-is-bridged -j ACCEPT;
    firewall-cmd --permanent --direct --passthrough ipv4 -D INPUT -j REJECT --reject-with icmp-host-prohibited

- name: Enable IPv4 Forwarding
  sysctl:
    name: net.ipv4.conf.all.forwarding
    value: 1
    sysctl_set: yes
    state: present

- name: Configure cni0 for control plane
  template:
    src: ifcfg-cni0.j2
    dest: /etc/sysconfig/network-scripts/ifcfg-cni0

- name: Configure eth0 for control plane
  template:
    src: ifcfg-eth0.j2
    dest: /etc/sysconfig/network-scripts/ifcfg-eth0
  notify: "restart net"

# Note:
# "restart net" sends DHCP request through eth0 for cni0.
# Currently DHCP client will use eth0's MAC, hence IP
# address should not changed.
